INSERT INTO HABITACIONES (ID,USUARIO_ID,CHECK_IN_DATE) VALUES (10,101,'2022-04-07');
INSERT INTO HABITACIONES (ID,USUARIO_ID,CHECK_IN_DATE) VALUES (20,539,'2022-04-15');
INSERT INTO HABITACIONES (ID,USUARIO_ID,CHECK_IN_DATE) VALUES (30,317,'2022-04-11');

INSERT INTO USUARIOS (ID,USUARIO_NOMBRE,USUARIO_APELLIDO,PAIS) VALUES (1,'Jaime','González','Mexico');
INSERT INTO USUARIOS (ID,USUARIO_NOMBRE,USUARIO_APELLIDO,PAIS) VALUES (2,'Ana','Santamaría','España');
INSERT INTO USUARIOS (ID,USUARIO_NOMBRE,USUARIO_APELLIDO,PAIS) VALUES (3,'Marina','Ugarte','Cuba');